name: translator_clean
description: "A new Flutter project."


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.7.0


dependencies:
  flutter:
    sdk: flutter
  translator: ^0.1.7
  shared_preferences: ^2.2.2
  flutter_spinkit: ^5.2.0
  speech_to_text: ^7.0.0
  flutter_tts: ^3.8.2 
  

  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.4


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter_icons :
  android: true 
  ios : true 
  image_path : "assets/icon.png"



  
flutter:


  uses-material-design: true

 
